# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f7bb151aca2b9ab0a57905abab9acbf5caf5d2b9632fddf1ca5c8b4c49f23a56d45dbf8525d0ef5c5f98b6d245f66688c2cd8105d090907afe3e3b1c34b303d
  origins: '*'
  resource: ('*', { :headers => :any, :methods => [:get, :post, :options] })

test:
  secret_key_base: ae631ddabe057a92c64ff45ecc9c4055d0cc6f7baffa3da8e2bae8a882c06604a9b157fc01d1ae53609f2b470170eab0945f23a84aa43cf3e73bd277aea7fa75
  origins: '*'
  resource: ('*', { :headers => :any, :methods => [:get, :post, :options] })

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  origins: '*'
  resource: ('*', { :headers => :any, :methods => [:get, :post, :options] })
